name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  lint-checks:
    name: Validate Markdown and Links
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js with version 18
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install markdownlint-cli
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      # Install markdown-link-check
      - name: Install markdown-link-check
        run: npm install -g markdown-link-check

      # Check Markdown syntax
      - name: Check Markdown syntax
        run: markdownlint '**/*.md'

      # Check for broken links
      - name: Check for broken links
        run: markdown-link-check '**/*.md'

  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: lint-checks

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install MkDocs
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build the MkDocs site
      - name: Build MkDocs site
        run: mkdocs build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          force_orphan: true
