name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  lint-checks:
    name: Validate Markdown and Links
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies for linting
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install markdownlint-cli markdown-link-check

      # Check Markdown syntax
      - name: Check Markdown syntax
        run: markdownlint '**/*.md'

      # Check for broken links
      - name: Check for broken links
        run: markdown-link-check '**/*.md'

  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: lint-checks

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install MkDocs
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      # Build the MkDocs site
      - name: Build MkDocs site
        run: mkdocs build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          force_orphan: true  # Ensure no conflicts with the existing branch
